"""Shared runner: back-test ONE strategy and write its results folder.

Every strategy folder (01_... to 06_...) defines its rule in ``strategy.py`` and calls
``run_strategy_folder``. That guarantees all six use the same data, the same SIP months,
the same instalment, the same costs and the same scoring, so their results are directly
comparable.
"""

from __future__ import annotations

from pathlib import Path
from typing import Callable

import pandas as pd

from . import plots
from .analysis import CRISES, crisis_table, rolling_windows
from .data import read_returns_table
from .engine import Strategy, contribution_schedule, run_sip
from .metrics import summarise

LOOKBACK = 120        # months of history the optimisers need -> SIPs start Feb 2010
AMOUNT = 10_000       # monthly instalment
COST_BPS = 10         # 0.10% cost on every trade
WINDOW_YEARS = 5      # length of each rolling SIP window (the SIP period is 10 years)
CURRENCY = "INR"

MONEY_COLS = {"Invested", "Final value"}
RATIO_COLS = {"Wealth multiple", "Sharpe", "Sharpe vs Liquid", "Sortino", "Calmar", "Windows"}


def fmt(df: pd.DataFrame, index: bool = True) -> str:
    """Markdown table: money with separators, ratios to 2 dp, other numbers as %."""
    out = df.copy()
    for c in out.columns:
        if out[c].dtype.kind != "f":
            continue
        if c in MONEY_COLS:
            out[c] = out[c].map(lambda v: f"{v:,.0f}")
        elif c in RATIO_COLS:
            out[c] = out[c].map(lambda v: f"{v:.2f}")
        elif c == "Annual cost drag":
            out[c] = out[c].map(lambda v: f"{v:.2%}")
        else:
            out[c] = out[c].map(lambda v: f"{v:.1%}")
    return out.to_markdown(index=index)


def sip_months(returns: pd.DataFrame) -> pd.PeriodIndex:
    """Common SIP window for every strategy: from the first month with 10 years of history."""
    return returns.index[LOOKBACK:]


def monthly_table(res, target: pd.DataFrame) -> pd.DataFrame:
    t = target.reindex(res.values.index)
    out = pd.DataFrame({
        "Instalment": res.contributions,
        "Total invested": res.contributions.cumsum(),
        **{f"{a} value": res.values[a] for a in res.values.columns},
        "Portfolio value": res.total,
        "Monthly return (TWR)": res.twr,
        **{f"{a} target weight": t[a] for a in t.columns},
        **{f"{a} actual weight": res.weights[a] for a in res.values.columns},
        "Bought": res.bought,
        "Sold": res.sold,
        "Costs": res.costs,
    })
    return out.rename_axis("Month")


def rolling_stats(roll: pd.DataFrame) -> pd.Series:
    x, dd = roll["XIRR"], roll["Worst wealth drop"]
    return pd.Series({
        "Windows": float(len(x)),
        "Median XIRR": x.median(),
        "5th pct XIRR": x.quantile(0.05),
        "Worst XIRR": x.min(),
        "Best XIRR": x.max(),
        "% windows losing money": (x < 0).mean(),
        "Median worst drop": dd.median(),
        "Worst drop (any window)": dd.min(),
    })


def run_strategy_folder(build: Callable[[pd.DataFrame], Strategy], folder: Path,
                        colour: str) -> dict:
    """Run the strategy on the prepared returns table and write ``folder/results/``."""
    rets = read_returns_table()
    strategy = build(rets)
    idx = sip_months(rets)
    contrib = contribution_schedule(idx, AMOUNT)
    res = run_sip(rets, strategy, contrib, COST_BPS)
    out = folder / "results"
    out.mkdir(parents=True, exist_ok=True)

    metrics = pd.Series(summarise(res, rf_returns=rets["Liquid"])).drop("Strategy").astype(float)
    roll = rolling_windows(rets, [strategy], str(idx[0]), WINDOW_YEARS,
                           amount=AMOUNT, cost_bps=COST_BPS)
    rstats = rolling_stats(roll)
    crisis = crisis_table([res], CRISES)[strategy.name].rename("Return")

    metrics.rename("Value").to_csv(out / "summary.csv")
    monthly_table(res, strategy.target).to_csv(out / "monthly.csv", float_format="%.6f")
    roll.drop(columns="Strategy").to_csv(out / f"rolling_{WINDOW_YEARS}y_windows.csv", index=False)
    crisis.to_csv(out / "crises.csv")

    plots.strategy_value_chart(res, out / "value.png", colour, CURRENCY)
    plots.strategy_drawdown_chart(res, out / "drawdown.png", colour)
    plots.allocation_chart(res, strategy.target, out / "allocation.png")

    md = [
        f"# {strategy.name}: results",
        f"SIP of ₹{AMOUNT:,}/month from {idx[0]} to {idx[-1]} ({len(idx)} instalments), "
        f"{COST_BPS} bps cost per trade. Generated by `strategy.py`.\n",
        "## Full period\n", fmt(metrics.to_frame("Value").T, index=False), "",
        f"## Every {WINDOW_YEARS}-year SIP window ({len(roll)} start dates)\n",
        fmt(rstats.to_frame("Value").T, index=False), "",
        "## Stress periods (cumulative return)\n",
        fmt(crisis.to_frame()), "",
        "Charts: `value.png`, `drawdown.png`, `allocation.png`. "
        "Month-by-month detail: `monthly.csv`.",
    ]
    (out / "summary.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    print(f"{strategy.name}: final {metrics['Final value']:,.0f} on "
          f"{metrics['Invested']:,.0f} | XIRR {metrics['XIRR']:.2%} | "
          f"Sharpe {metrics['Sharpe']:.2f} (vs Liquid {metrics['Sharpe vs Liquid']:.2f}) | worst fall {metrics['Worst wealth drop']:.1%}")
    return {"metrics": metrics, "rolling": rstats, "crisis": crisis, "result": res,
            "strategy": strategy}
